### PR TITLE
TOKENN!

### PR DESCRIPTION
**Pull request by ghost**
take away the token! someone can log into the bot LOL

### CODE REVIEW

**Comment by Jminding** [comment]
You need the token to be there

**Comment by Jminding** [comment]
Ima take it out in the repo though

**Comment by ghost** [comment]
Yeah I know you need it, just saying someone can steal your bot and that's could be dangerous

**Comment by Jminding** [comment]
I switched it out for 
```javascript
const TOKEN = process.env.TOKEN;
client.login(TOKEN); // a more secure way for the token (since this code is going on GitHub)
```

**Comment by ghost** [comment]
Yeah ok that's great

**Pull request closed without merging**
